create database network_analytics;
use network_analytics;
CREATE TABLE network_logs (
    log_id INT,
    timestamp DATETIME,
    vlan_id VARCHAR(20),
    department VARCHAR(50),
    device_type VARCHAR(50),
    protocol VARCHAR(20),
    bandwidth_mb INT,
    packet_loss_percent DECIMAL(5,2),
    downtime_minutes INT,
    threat_flag VARCHAR(10),
    location VARCHAR(50)
);
select*
from network_logs
limit 10;

-- count total network log entries in the dataset
select count(*) as total_logs
from network_logs;

--  count total network threats flagged
select count(*) as total_threats 
from network_logs
where threat_flag = 'yes';

select sum(downtime_minutes) as total_downtime
from network_logs;

-- analyze total bandwidth consumption across departments
select
	department,
    sum(bandwidth_mb) as total_bandwidth
    from network_logs
    group by department
    order by total_bandwidth desc;
    
  -- Evaluate average packet loss for each VLAN  
select 
vlan_id,
	round(avg(packet_loss_percent),2) as avg_packet_loss
from network_logs
group by vlan_id
order by avg_packet_loss desc;

-- analyze peak network traffic hours
select
	hour(timestamp) as hour_of_day,
    round(avg(bandwidth_mb),2) as avg_traffic
    from network_logs
    group by hour_of_day
    order by avg_traffic desc;
  
  -- Identify protocols associated with the highest number of security threats
select
	protocol,
    count(*) as threat_count
    from network_logs
    where threat_flag = 'yes'
    group by protocol
    order by threat_count desc;
   
   --  Compare total downtime across company branch locations
select
	location,
    sum(downtime_minutes) as total_downtime
    from network_logs
    group by location
    order by total_downtime desc;
    
    -- Analyze average bandwidth usage generated by different device types
select 
	device_type,
    round(avg(bandwidth_mb),2) as avg_usage
    from network_logs
    group by device_type
    order by avg_usage desc;
    
    




